name: Flutter Web

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    container:
      image:  cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.2'
      - run: flutter pub get
      - run: flutter test
