name: Flutter Web

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:v1.9.1-hotfix.1-web
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: flutter pub ge
      - name: Run tests
        run: flutter test