name: Flutter Web

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    container:
      image:  cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v1
      - name: PWD
        run: echo ${PWD}
      - name: Install dependencies
        run: pwd && ls -la && sudo su - && sudo chown -R cirrus:cirrus ./ && flutter pub get
      - name: Run tests
        run: flutter test