name: Flutter Web

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:stable
      volumes:
        - /__w/integrated-flutter-web/integrated-flutter-web:/build
      options: --workdir /build
    steps:
      - uses: actions/checkout@v1
      - name: PWD
        run: echo ${PWD}
      - name: Install dependencies
        run: pwd && ls -la && flutter pub get
      - name: Run tests
        run: flutter test